export type Resource = {
  id: string;
  title: string;
  description: string;
  type: 'video' | 'audio' | 'guide';
  tags: string[];
  imagePlaceholderId: string;
  url: string;
};

export const resources: Resource[] = [
  {
    id: 'res-1',
    title: 'Introduction to Mindfulness Meditation',
    description: 'Learn the basics of mindfulness meditation in this guided video session. Perfect for beginners looking to reduce stress.',
    type: 'video',
    tags: ['Mindfulness', 'Stress Management', 'Anxiety Relief'],
    imagePlaceholderId: 'img-1',
    url: '#',
  },
  {
    id: 'res-2',
    title: 'Deep Breathing Exercises for Calm',
    description: 'An audio guide to deep breathing techniques that can help you find calm and center yourself during anxious moments.',
    type: 'audio',
    tags: ['Anxiety Relief', 'Stress Management'],
    imagePlaceholderId: 'img-2',
    url: '#',
  },
  {
    id: 'res-3',
    title: 'Your Guide to a Better Night\'s Sleep',
    description: 'This comprehensive guide covers tips and strategies for improving your sleep hygiene and getting more restful sleep.',
    type: 'guide',
    tags: ['Sleep Improvement', 'Healthy Habits'],
    imagePlaceholderId: 'img-3',
    url: '#',
  },
  {
    id: 'res-4',
    title: 'The 5-Minute Morning Journal',
    description: 'Start your day with intention and gratitude. This guide provides prompts for a quick and effective morning journaling practice.',
    type: 'guide',
    tags: ['Mindfulness', 'Self-Care', 'Healthy Habits'],
    imagePlaceholderId: 'img-4',
    url: '#',
  },
  {
    id: 'res-5',
    title: 'Yoga for Stress Relief',
    description: 'A gentle 30-minute yoga flow designed to release tension from your body and mind. Suitable for all levels.',
    type: 'video',
    tags: ['Stress Management', 'Mindfulness', 'Healthy Habits'],
    imagePlaceholderId: 'img-5',
    url: '#',
  },
  {
    id: 'res-6',
    title: 'Understanding Cognitive Behavioral Therapy (CBT)',
    description: 'An introductory guide to the principles of CBT and how it can be used to manage depression and anxiety.',
    type: 'guide',
    tags: ['Depression Support', 'Anxiety Relief'],
    imagePlaceholderId: 'img-6',
    url: '#',
  },
  {
    id: 'res-7',
    title: 'Body Scan Meditation for Relaxation',
    description: 'This guided audio meditation helps you connect with your body and release physical tension, promoting deep relaxation.',
    type: 'audio',
    tags: ['Mindfulness', 'Sleep Improvement'],
    imagePlaceholderId: 'img-7',
    url: '#',
  },
  {
    id: 'res-8',
    title: 'Building Healthy Relationships',
    description: 'Explore the foundations of healthy communication and boundaries in this guide to improving your relationships.',
    type: 'guide',
    tags: ['Relationships', 'Communication'],
    imagePlaceholderId: 'img-8',
    url: '#',
  },
  {
    id: 'res-9',
    title: 'Overcoming Procrastination',
    description: 'A video guide with practical strategies to help you stop procrastinating and improve your focus and productivity.',
    type: 'video',
    tags: ['Focus', 'Productivity', 'Healthy Habits'],
    imagePlaceholderId: 'img-9',
    url: '#',
  },
  {
    id: 'res-10',
    title: 'Sounds of Nature: Rainforest Ambience',
    description: 'Relax or focus with this 1-hour audio recording of gentle rainforest sounds. Ideal for studying or unwinding.',
    type: 'audio',
    tags: ['Stress Management', 'Focus', 'Sleep Improvement'],
    imagePlaceholderId: 'img-10',
    url: '#',
  },
  {
    id: 'res-11',
    title: 'The Art of Saying No',
    description: 'Learn how to set healthy boundaries and prioritize your well-being by confidently saying no.',
    type: 'guide',
    tags: ['Self-Care', 'Relationships', 'Communication'],
    imagePlaceholderId: 'img-11',
    url: '#',
  },
  {
    id: 'res-12',
    title: 'Mindful Eating Exercise',
    description: 'A short audio guide to practice mindful eating, helping you develop a healthier relationship with food.',
    type: 'audio',
    tags: ['Mindfulness', 'Healthy Habits'],
    imagePlaceholderId: 'img-12',
    url: '#',
  },
  {
    id: 'res-13',
    title: 'Dealing with Exam Stress',
    description: 'A guide specifically for students on how to manage and reduce stress during exam periods.',
    type: 'guide',
    tags: ['Stress Management', 'Anxiety Relief', 'Focus'],
    imagePlaceholderId: 'img-13',
    url: '#',
  },
  {
    id: 'res-14',
    title: 'Animated Guide to a Panic Attack',
    description: 'This short animated video explains what happens during a panic attack and what you can do to cope.',
    type: 'video',
    tags: ['Anxiety Relief'],
    imagePlaceholderId: 'img-14',
    url: '#',
  },
  {
    id: 'res-15',
    title: 'How to Build Resilience',
    description: 'This guide offers practical advice and exercises to help you build mental and emotional resilience to navigate life\'s challenges.',
    type: 'guide',
    tags: ['Resilience', 'Self-Care'],
    imagePlaceholderId: 'img-15',
    url: '#',
  },
  {
    id: 'res-16',
    title: 'Walking Meditation',
    description: 'Learn how to practice mindfulness while walking with this guided audio session.',
    type: 'audio',
    tags: ['Mindfulness', 'Stress Management', 'Healthy Habits'],
    imagePlaceholderId: 'img-16',
    url: '#',
  },
  {
    id: 'res-17',
    title: 'Social Anxiety: Tips & Strategies',
    description: 'A video guide with actionable tips for managing social anxiety and feeling more comfortable in social situations.',
    type: 'video',
    tags: ['Anxiety Relief', 'Relationships'],
    imagePlaceholderId: 'img-17',
    url: '#',
  },
  {
    id: 'res-18',
    title: 'Beginner\'s Guide to Journaling',
    description: 'Discover different journaling techniques and find the one that works best for you to process your thoughts and emotions.',
    type: 'guide',
    tags: ['Self-Care', 'Depression Support', 'Mindfulness'],
    imagePlaceholderId: 'img-18',
    url: '#',
  },
  {
    id: 'res-19',
    title: 'Positive Affirmations for Self-Esteem',
    description: 'Listen to these positive affirmations to help boost your self-esteem and cultivate a more positive self-image.',
    type: 'audio',
    tags: ['Self-Care', 'Depression Support', 'Resilience'],
    imagePlaceholderId: 'img-19',
    url: '#',
  },
  {
    id: 'res-20',
    title: 'Time Management Techniques for Students',
    description: 'Improve your productivity and reduce stress with these effective time management strategies tailored for students.',
    type: 'guide',
    tags: ['Focus', 'Productivity', 'Stress Management'],
    imagePlaceholderId: 'img-20',
    url: '#',
  },
];

export const allTags = Array.from(new Set(resources.flatMap(r => r.tags))).sort();
